// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Required for JSON deserialization", Scope = "member", Target = "~M:Pacifica.Json.MyEMSLFileInfo.#ctor(System.String,System.Int64,System.String,System.DateTime)")]
[assembly: SuppressMessage("Performance", "RCS1197:Optimize StringBuilder.Append/AppendLine call.", Justification = "Optimization not necessary", Scope = "module")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary", Justification = "Parentheses not required", Scope = "member", Target = "~M:Pacifica.DataUpload.TarStreamUploader.CreateTarArchive(System.IO.Stream,Pacifica.Core.Configuration,System.Collections.Generic.SortedDictionary{System.String,Pacifica.Core.FileInfoObject},System.IO.FileInfo,System.Int64)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary", Justification = "Parentheses not required", Scope = "member", Target = "~M:Pacifica.DataUpload.TarStreamUploader.SendFileListToIngester(Pacifica.Core.Configuration,System.String,System.String,System.Collections.Generic.SortedDictionary{System.String,Pacifica.Core.FileInfoObject},System.String,Pacifica.DataUpload.TarStreamUploader.UploadDebugMode)~System.String")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary", Justification = "Parentheses not required", Scope = "member", Target = "~M:Pacifica.DMSDataUpload.MyEMSLUploader.Container_ProgressEvent(System.String,System.Single)")]
[assembly: SuppressMessage("Roslynator", "RCS1123:Add parentheses when necessary", Justification = "Parentheses not required", Scope = "member", Target = "~M:Pacifica.DMSDataUpload.MyEMSLUploader.MyEMSLUpload_StatusUpdate(System.Object,Pacifica.Core.StatusEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:Pacifica.DMSDataUpload.DMSMetadataObject.#ctor(Pacifica.Core.Configuration,System.String,System.Int32,PRISM.FileTools)")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:Pacifica.DMSDataUpload.DMSMetadataObject.CompareDatasetContentsWithMyEMSLMetadata(System.String,System.Collections.Generic.IEnumerable{Pacifica.Core.FileInfoObject},Pacifica.DataUpload.Upload.UploadMetadata,System.Boolean@,System.String@)~System.Collections.Generic.List{Pacifica.Core.FileInfoObject}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:Pacifica.DMSDataUpload.DMSMetadataObject.GetDatasetFilesInMyEMSL(System.Int32,System.String)~System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{Pacifica.Json.MyEMSLFileInfo}}")]
[assembly: SuppressMessage("Style", "IDE0270:Use coalesce expression", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:Pacifica.Core.EasyHttp.GetFile(Pacifica.Core.Configuration,System.String,System.Net.CookieContainer,System.Net.HttpStatusCode@,System.String,System.Int32,System.Net.NetworkCredential)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:Pacifica.DMSDataUpload.DMSMetadataObject.CollectFileInformation(Pacifica.DMSDataUpload.DMSMetadataObject.ArchiveModes,System.String,System.String,System.Boolean)~System.Collections.Generic.List{Pacifica.Core.FileInfoObject}")]
