// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Keep for reference", Scope = "member", Target = "~M:MyEMSLReader.Downloader.DownloadAndExtractTarFile(System.Net.CookieContainer,System.Collections.Generic.IReadOnlyCollection{MyEMSLReader.ArchivedFileInfo},System.Int64,System.Collections.Generic.IReadOnlyDictionary{System.Int64,System.String},System.IO.FileSystemInfo,MyEMSLReader.Downloader.DownloadLayout,System.String,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.DataPackageListInfo.#ctor")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.DatasetInfoBase.#ctor")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.DatasetInfoBase.FindFiles(System.String,System.String,System.String,System.Int32,System.String,System.Boolean,System.Boolean)~System.Collections.Generic.List{MyEMSLReader.DatasetDirectoryOrFileInfo}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.DatasetListInfo.AddDataset(System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.DatasetListInfoByID.#ctor")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.Downloader.DownloadFilesDirectly(System.Collections.Generic.IReadOnlyDictionary{System.Int64,MyEMSLReader.ArchivedFileInfo},System.Net.CookieContainer,System.Collections.Generic.IReadOnlyDictionary{System.Int64,System.String},System.IO.FileSystemInfo,MyEMSLReader.Downloader.DownloadLayout,System.Int64@)~System.Collections.Generic.Dictionary{System.Int64,System.String}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.DownloadQueue.#ctor")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.Reader.FilterSearchResults(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.SortedSet{System.String}},System.Boolean,System.Collections.Generic.IEnumerable{MyEMSLReader.ArchivedFileInfo},System.Boolean)~System.Collections.Generic.List{MyEMSLReader.ArchivedFileInfo}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.Reader.FindFilesByDataset(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.SortedSet{System.String}},System.Boolean,System.String,System.Collections.Generic.IEnumerable{System.Collections.Generic.KeyValuePair{System.String,System.String}})~System.Collections.Generic.List{MyEMSLReader.ArchivedFileInfo}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.Reader.RunItemSearchQuery(PRISMDatabaseUtils.IDBTools,System.String,System.String,System.Int32)~System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{MyEMSLReader.ArchivedFileInfo}}")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:MyEMSLReader.DatasetInfoBase.FindFiles(System.String,System.String,System.String,System.Int32,System.String,System.Boolean,System.Boolean)~System.Collections.Generic.List{MyEMSLReader.DatasetDirectoryOrFileInfo}")]
